# export DEBEZIUM_VERSION=2.4
version: '2'
name: play

services:

  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  mongodb:
    image: quay.io/debezium/example-mongodb:${DEBEZIUM_VERSION}
    hostname: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGODB_USER=dbuser
      - MONGODB_PASSWORD=dbpass
    volumes:
      - ./mongo-config:/usr/local/bin/mongo-config

  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
      - 8083:8083
    links:
      - kafka
      - mongodb
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    volumes:
     - ./connectors/debezium-connector-2.4:/kafka/connect/debezium-connector-mongodb
     - ./connectors/mongodb-connector:/kafka/connect/mongodb-connector
